export const statusCodes = {
  global: [
    {
      type: 'Unauthorized',
      code: 401,
      message: 'Unauthorized',
      error: true,
    },
  ],
  paymentsModule: [
    {
      type: 'SUCCESS',
      code: 0,
      message: 'Successful',
      error: false,
    },
    {
      type: 'RECORD_FOUND',
      code: 0,
      message: 'RECORD FOUND',
      error: false,
    },
    {
      type: 'FOUND_ACCOUNT_DETAILS',
      code: 0,
      message: 'Found account details',
      error: false,
    },
    {
      type: 'ACTIVATED',
      code: 1,
      message: 'Activated',
      error: false,
    },
    {
      type: 'ABORTED',
      code: 12,
      message: 'User Aborted Transaction',
      error: true,
    },
    {
      type: 'INVALID_HASH_VALUE',
      code: 13,
      message: 'The hash value of the parameters do not match',
      error: true,
    },
    {
      type: 'TRANSACTION_FAILED',
      code: 2,
      message: 'Transaction Failed',
      error: false,
    },
    {
      type: 'AUTHENTICATION_ERROR',
      code: 20,
      message: 'Invalid User Authentication',
      error: true,
    },
    {
      type: 'PENDING',
      code: 21,
      message: 'Transaction Pending',
      error: false,
    },
    {
      type: 'INVALID_REQUEST',
      code: 22,
      message: 'Invalid Request',
      error: true,
    },
    {
      type: 'INVALID_RRR',
      code: 22,
      message: 'Invalid RRR',
      error: true,
    },
    {
      type: 'INVALID_SERVICE_MERCHANT',
      code: 23,
      message: 'Service type or Merchant Does not Exist',
      error: true,
    },
    {
      type: 'INVALID_MERCHANT_ORDERID',
      code: 23,
      message: 'Invalid Merchant or OrderId',
      error: true,
    },
    {
      type: 'MERCHANT_STATUS_ERROR',
      code: 24,
      message: 'Inactive Merchant',
      error: true,
    },
    {
      type: 'REFRENCE_GENERATED',
      code: 25,
      message: 'Payment Reference generated',
      error: false,
    },
    {
      type: 'UNKNOWN_ORDER',
      code: 26,
      message: 'No such Order Request',
      error: true,
    },
    {
      type: 'ALREADY_PROCESSED',
      code: 27,
      message: 'Transaction Already Processed',
      error: true,
    },
    {
      type: 'DUPLICATE_REQUEST',
      code: 28,
      message: 'Duplicate Order Ref',
      error: true,
    },
    {
      type: 'INVALID_BANKCODE',
      code: 29,
      message: 'Invalid Bank Code',
      error: true,
    },
    {
      type: 'NO_FUND',
      code: 30,
      message: 'Insufficent Funds',
      error: true,
    },
    {
      type: 'NO_ACCOUNT',
      code: 31,
      message: 'No Funding Account',
      error: true,
    },
    {
      type: 'INVALID_DATEFORMAT',
      code: 32,
      message: 'Invalid Date Format',
      error: true,
    },
    {
      type: 'INVALID_AUTHTOKEN',
      code: 33,
      message: 'Invalid Authentication Token',
      error: true,
    },
    {
      type: 'INVALID_FUNDINGSOURCE',
      code: 34,
      message: 'Invalid Funding Source',
      error: true,
    },
    {
      type: 'LIMIT_EXCEEDED',
      code: 35,
      message: 'Payment Limit Exceeded',
      error: true,
    },
    {
      type: 'DUPLICATE_UNIQUEREF',
      code: 36,
      message: 'Duplicate Unique Reference',
      error: true,
    },
    {
      type: 'DUPLICATE_TRANSACTION_ID',
      code: 36,
      message: 'Duplicate Transaction ID',
      error: true,
    },
    {
      type: 'DUPLICATE_lINEITEM',
      code: 37,
      message: 'Duplicate Line Item ID',
      error: true,
    },
    {
      type: 'LOW_AMOUNT',
      code: 38,
      message: 'Processing Fees exceeds Amount Specified',
      error: true,
    },
    {
      type: 'INVALID_PAYMENT_MODE',
      code: 39,
      message: 'Invalid Payment Mode Type Supplied',
      error: true,
    },
    {
      type: 'REQUEST_OK',
      code: 40,
      message: 'Initail Request OK',
      error: false,
    },
    {
      type: 'TRANSACTION_FORWARDED',
      code: 41,
      message: 'Transaction Forwarded for Processing',
      error: false,
    },
    {
      type: 'COMPANY_NOTONTOPUP',
      code: 42,
      message: 'You are not enabled for Account Transfer',
      error: true,
    },
    {
      type: 'INACTIVE_SERVICETYPE',
      code: 43,
      message: 'Service Type is not Valid',
      error: true,
    },
    {
      type: 'INVALID_INTEGRATION_SERVICETYPE',
      code: 44,
      message: 'Service Type is not Enabled for Integration',
      error: true,
    },
    {
      type: 'AWAITING_PAYMENT_CONFIRMATION',
      code: 45,
      message: 'Awaiting Payment Confirmation',
      error: false,
    },
    {
      type: 'TRUNCATED',
      code: 46,
      message: 'User Truncate Transaction',
      error: true,
    },
    {
      type: 'REFERENCE_WITH_RRR',
      code: 55,
      message: 'RRR Already Exist for the orderId',
      error: true,
    },
    {
      type: 'UNMAPPED_MERCHANT_SERVICETYPEID',
      code: 56,
      message: 'Service Type is not Mapped to the Merchant',
      error: true,
    },
    {
      type: 'UNPROFILLED_ACCOUNT_NUMBER',
      code: 57,
      message: 'Beneficiary Account Number is not Registered on Remita',
      error: true,
    },
    {
      type: 'PENDING_APPROVAL',
      code: 58,
      message: 'Pending Authorization',
      error: true,
    },
    {
      type: 'REJECTED',
      code: 59,
      message: 'Rejected',
      error: true,
    },
    {
      type: 'INACTIVE_MANDATE',
      code: 61,
      message: 'Mandate Not Activated',
      error: true,
    },
    {
      type: 'INVALID_MANDATE',
      code: 61,
      message: 'Mandate Not Valid',
      error: true,
    },
    {
      type: 'MANDATE_NOT_DUE',
      code: 62,
      message: 'Mandate Not Due',
      error: true,
    },
    {
      type: 'EXPIRED_MANDATE',
      code: 63,
      message: 'Expired Mandate',
      error: true,
    },
    {
      type: 'INTEGRATION_AMOUNT',
      code: 64,
      message: 'Amount supplied is low',
      error: true,
    },
    {
      type: 'INVALID_SUB_MERCHANT_SERVICES',
      code: 65,
      message: 'Sub Merchant not premited to proces Service Type',
      error: true,
    },
    {
      type: 'MANDATE_DEACTIVATED',
      code: 66,
      message: 'Mandate Deactivated',
      error: true,
    },
    {
      type: 'DIRECTDEBIT',
      code: 67,
      message: 'Only Direct Debit Mandate Allowed',
      error: true,
    },
    {
      type: 'WALLET_ERROR',
      code: 68,
      message: 'Wallet Could not be Validated',
      error: true,
    },
    {
      type: 'NEW',
      code: 69,
      message: 'New Transaction',
      error: false,
    },
    {
      type: 'AWAITING_DEBIT',
      code: 70,
      message: 'Awaiting Debit',
      error: false,
    },
    {
      type: 'UNDERGOING_BANK_PROCESSING',
      code: 71,
      message: 'Undergoing Bank Processing',
      error: false,
    },
    {
      type: 'PENDING_CREDIT',
      code: 72,
      message: 'Pending Credit',
      error: false,
    },
    {
      type: 'INVALID_MANDATE_TYPE',
      code: 73,
      message: 'Invalid Mandate Type',
      error: true,
    },
    {
      type: 'NO_AVAILABLE_RECORD',
      code: 74,
      message: 'NO AVAILABLE RECORD',
      error: true,
    },
    {
      type: 'ALREADY_ACTIVATED',
      code: 75,
      message: 'Mandate is Already Active',
      error: true,
    },
    {
      type: 'MANDATE_MAX_NUMBER_ERROR',
      code: 76,
      message: 'Mandate Maximum Number of Times Exceeded',
      error: true,
    },
    {
      type: 'UNKNOWN_ACCOUNT',
      code: 81,
      message: 'Unknown account',
      error: true,
    },
    {
      type: 'ACCOUNT_ALREADY_DEACTIVATED',
      code: 82,
      message: 'Account Already Deactivated',
      error: true,
    },
    {
      type: 'ACCOUNT_ALREADY_EXIST',
      code: 82,
      message: 'Account Already Exist',
      error: true,
    },
    {
      type: 'INVALID_TIN',
      code: 83,
      message: 'Invalid Tin Number',
      error: true,
    },
    {
      type: 'INVALID_TOTAL_LINE_ITEMS_AMOUNT',
      code: 84,
      message: 'Total Amount Does not Match with Line Items Amount',
      error: true,
    },
    {
      type: 'ACCOUNT_NOT_LINKED_WITH_MERCHANT',
      code: 85,
      message: 'Bank account not linked with merchant',
      error: true,
    },
    {
      type: 'ACCOUNT_NOT_ACTIVE',
      code: 86,
      message: 'Bank account not active',
      error: true,
    },
    {
      type: 'DUPLICATE_CHARGE_FEE',
      code: 87,
      message: 'More than one chargeFee set to true',
      error: true,
    },
    {
      type: 'CHARGE_FEE_NOT_SET',
      code: 88,
      message: 'ChargeFee not set',
      error: true,
    },
    {
      type: 'UNMATCH_AMOUNT',
      code: 89,
      message: 'Amount does not match',
      error: true,
    },
    {
      type: 'INVALID_AMOUNT',
      code: 90,
      message: 'Invalid total or beneficiary amount',
      error: true,
    },
    {
      type: 'UNPROFILED_ACCOUNT_WITH_BANK_CODE',
      code: 91,
      message:
        'Beneficiary Account Number is not profiled with supplied bank code on Remita',
      error: true,
    },
    {
      type: 'INVALID_RESPONSE_URL',
      code: 92,
      message: 'ResponseUrl is Empty;',
      error: true,
    },
    {
      type: 'ERROR_PROCESSING_REQUEST',
      code: 25,
      message: 'Error Processing Request',
      error: true,
    },
    {
      type: 'DEACTIVATED',
      code: 659,
      message: 'Deactivated',
      error: true,
    },
    {
      type: 'CHANNEL_RESPONSE_UNMAPPED',
      code: 997,
      message: 'Payment Gateway Unsucessful',
      error: true,
    },
    {
      type: 'INTERNAL_ERROR',
      code: 998,
      message: 'An internal Error Occured',
      error: true,
    },
    {
      type: 'UNKNOWN',
      code: 999,
      message: 'Unknown Error',
      error: true,
    },
  ],
  fundsTransferModule: [
    {
      code: 0,
      message: 'Approved or completed successfully',
      error: false,
    },
    {
      code: 1,
      message: 'Status unknown, please wait for settlement report',
      error: true,
    },
    {
      code: 7,
      message: 'Invalid Account',
      error: true,
    },
    {
      code: 9,
      message: 'Request processing in progress',
      error: true,
    },
    {
      code: 12,
      message: 'Invalid transaction',
      error: true,
    },
    {
      code: 16,
      message: 'Unknown Bank Code',
      error: true,
    },
    {
      code: 21,
      message: 'No action is taken',
      error: true,
    },
    {
      code: 52,
      message: 'Insufficient funds',
      error: true,
    },
    {
      code: 61,
      message: 'Transfer limit Exceeded',
      error: true,
    },
    {
      code: 69,
      message: 'Unsuccessful Account/Amount block',
      error: true,
    },
    {
      code: 70,
      message: 'Unsuccessful Account/Amount unblock',
      error: true,
    },
    {
      code: 94,
      message: 'Duplicate transaction',
      error: true,
    },
    {
      code: 96,
      message: 'System malfunction',
      error: true,
    },
    {
      code: 97,
      message: 'Timeout waiting for a response from destination',
      error: true,
    },
    {
      code: 98,
      message: 'Account already exists',
      error: true,
    },
    {
      code: 99,
      message: 'Invalid Source Account',
      error: true,
    },
    {
      code: 100,
      message: 'Invalid Beneficiary Account',
      error: true,
    },
    {
      code: 101,
      message: 'Unsuccessful Source Account/Amount block',
      error: true,
    },
    {
      code: 102,
      message: 'Unsuccessful Source Account/Amount block',
      error: true,
    },
    {
      code: 103,
      message: 'Debit ok',
      error: false,
    },
  ],
  referenceDataModule: [
    {
      code: 0,
      message: 'SUCCESS',
      error: false,
    },
    {
      code: 1,
      message: 'TRANSACTION_FAILED',
      error: true,
    },
    {
      code: 2,
      message: 'Bad Request',
      error: true,
    },
    {
      code: 4,
      message: 'AUTHENTICATION_ERROR',
      error: true,
    },
    {
      code: 6,
      message: 'System error',
      error: true,
    },
    {
      code: 7,
      message: 'Limit reached',
      error: true,
    },
    {
      code: 8,
      message: 'Unknown payment reference',
      error: true,
    },
    {
      code: 10,
      message: 'Insufficient amount',
      error: true,
    },
    {
      code: 12,
      message: 'Resource not found',
      error: true,
    },
    {
      code: 13,
      message: 'Duplicate Request',
      error: true,
    },
    {
      code: 14,
      message: 'Authentication Expired',
      error: true,
    },
    {
      code: 22,
      message: 'Unknown transaction',
      error: true,
    },
    {
      code: 23,
      message: 'Already processed transaction',
      error: true,
    },
    {
      code: 24,
      message: 'Invalid Request.Missing headers or parameters',
      error: true,
    },
    {
      code: 25,
      message: 'Error Processing Request',
      error: true,
    },
    {
      code: 26,
      message: 'Unknown merchant',
      error: true,
    },
    {
      code: 28,
      message: 'Unknown bank account',
      error: true,
    },
    {
      code: 31,
      message: 'Invalid credit account',
      error: true,
    },
    {
      code: 32,
      message: 'Missing request parameters',
      error: true,
    },
    {
      code: 34,
      message: 'Api autorization error',
      error: true,
    },
    {
      code: 36,
      message: 'Invalid request time stamp format',
      error: true,
    },
    {
      code: 40,
      message: 'MandateSetUp failed',
      error: true,
    },
    {
      code: 41,
      message: 'Mandate Activation failed',
      error: true,
    },
    {
      code: 42,
      message: 'UNAUTHORIZED API ACCESS',
      error: true,
    },
    {
      code: 46,
      message: 'PERMISSION REQUIRED',
      error: true,
    },
    {
      code: 47,
      message: 'INVOICE NOT FOUND',
      error: true,
    },
    {
      code: 48,
      message: 'INVOICE ALREADY PROCESSED',
      error: true,
    },
    {
      code: 50,
      message: 'INSUFFICIENT WALLET BALANCE',
      error: true,
    },
    {
      code: 51,
      message: 'WALLET NOT CONFIFURED FOR MERCHANT',
      error: true,
    },
    {
      code: 52,
      message: 'WALLET LIMIT EXCEEDED',
      error: true,
    },
    {
      code: 53,
      message: 'INVALID TSA SERVICE ID',
      error: true,
    },
    {
      code: 54,
      message: 'INVALID AMOUNT',
      error: true,
    },
    {
      code: 57,
      message: 'Amount Value greater than Total RRR Amount cannot be processed',
      error: true,
    },
    {
      code: 58,
      message: 'IP NOT PERMITTED',
      error: true,
    },
    {
      code: 59,
      message: 'Invalid Bank Code Supplied',
      error: true,
    },
    {
      code: 60,
      message: 'Invalid Account Number Supplied',
      error: true,
    },
    {
      code: 61,
      message: 'Api Hashing',
      error: true,
    },
  ],
  inflightCollectionsModule: [
    {
      code: 0,
      message: 'Transaction Completed Successfully (Record Found)',
      error: false,
    },
    {
      code: 1,
      message: 'Approved (Direct Debit Instruction Successful)',
      error: false,
    },
    {
      code: 13,
      message: 'Duplicate Request',
      error: true,
    },
    {
      code: 20,
      message: 'Authentication Error (Invalid User Authentication)',
      error: true,
    },
    {
      code: 25,
      message: 'Error Processing Request',
      error: true,
    },
    {
      code: 34,
      message: 'Invalid funding Source',
      error: true,
    },
    {
      code: 40,
      message: 'Initial Request OK (Mandate Setup Completed Successfully)',
      error: true,
    },
    {
      code: 41,
      message: 'Invalid Authorisation ID',
      error: true,
    },
    {
      code: 61,
      message: 'Invalid Mandate',
      error: true,
    },
    {
      code: 62,
      message: 'Mandate Not Due',
      error: true,
    },
    {
      code: 63,
      message: 'Expired Mandate',
      error: true,
    },
    {
      code: 66,
      message: 'Mandate Deactivated',
      error: true,
    },
    {
      code: 67,
      message: 'Only Direct Debit Mandate Allowed',
      error: true,
    },
    {
      code: 69,
      message: 'New Transaction',
      error: false,
    },
    {
      code: 70,
      message: 'Awaiting Debit',
      error: true,
    },
    {
      code: 71,
      message: 'Undergoing Bank Processing',
      error: true,
    },
    {
      code: 72,
      message: 'Pending Credit',
      error: true,
    },
    {
      code: 73,
      message: 'Invalid Mandate Type',
      error: true,
    },
    {
      code: 74,
      message: 'No Available Record',
      error: true,
    },
    {
      code: 75,
      message: 'Mandate Already Active',
      error: true,
    },
  ],
  billerAggregationModule: [
    {
      code: 0,
      message: 'SUCCESS',
      error: false,
    },
    {
      code: 1,
      message: 'TRANSACTION_FAILED',
      error: true,
    },
    {
      code: 2,
      message: 'Bad Request',
      error: true,
    },
    {
      code: 4,
      message: 'AUTHENTICATION_ERROR',
      error: true,
    },
    {
      code: 6,
      message: 'System error',
      error: true,
    },
    {
      code: 7,
      message: 'Limit reached',
      error: true,
    },
    {
      code: 8,
      message: 'Unknown payment reference',
      error: true,
    },
    {
      code: 10,
      message: 'Insufficient amount',
      error: true,
    },
    {
      code: 12,
      message: 'Resource not found',
      error: true,
    },
    {
      code: 13,
      message: 'Duplicate Request',
      error: true,
    },
    {
      code: 14,
      message: 'Authentication Expired',
      error: true,
    },
    {
      code: 22,
      message: 'Unknown transaction',
      error: true,
    },
    {
      code: 23,
      message: 'Already processed transaction',
      error: true,
    },
    {
      code: 24,
      message: 'Invalid Request.Missing headers or parameters',
      error: true,
    },
    {
      code: 25,
      message: 'Error Processing Request',
      error: true,
    },
    {
      code: 26,
      message: 'Unknown merchant',
      error: true,
    },
    {
      code: 28,
      message: 'Unknown bank account',
      error: true,
    },
    {
      code: 31,
      message: 'Invalid credit account',
      error: true,
    },
    {
      code: 32,
      message: 'Missing request parameters',
      error: true,
    },
    {
      code: 34,
      message: 'Api autorization error',
      error: true,
    },
    {
      code: 36,
      message: 'Invalid request time stamp format',
      error: true,
    },
    {
      code: 40,
      message: 'MandateSetUp failed',
      error: true,
    },
    {
      code: 41,
      message: 'Mandate Activation failed',
      error: true,
    },
    {
      code: 42,
      message: 'UNAUTHORIZED API ACCESS',
      error: true,
    },
    {
      code: 46,
      message: 'PERMISSION REQUIRED',
      error: true,
    },
    {
      code: 47,
      message: 'INVOICE NOT FOUND',
      error: true,
    },
    {
      code: 48,
      message: 'INVOICE ALREADY PROCESSED',
      error: true,
    },
    {
      code: 50,
      message: 'INSUFFICIENT WALLET BALANCE',
      error: true,
    },
    {
      code: 51,
      message: 'WALLET NOT CONFIFURED FOR MERCHANT',
      error: true,
    },
    {
      code: 52,
      message: 'WALLET LIMIT EXCEEDED',
      error: true,
    },
    {
      code: 53,
      message: 'INVALID TSA SERVICE ID',
      error: true,
    },
    {
      code: 54,
      message: 'INVALID AMOUNT',
      error: true,
    },
    {
      code: 57,
      message: 'Amount Value greater than Total RRR Amount cannot be processed',
      error: true,
    },
    {
      code: 58,
      message: 'IP NOT PERMITTED',
      error: true,
    },
    {
      code: 59,
      message: 'Invalid Bank Code Supplied',
      error: true,
    },
    {
      code: 60,
      message: 'Invalid Account Number Supplied',
      error: true,
    },
    {
      code: 61,
      message: 'Api Hashing',
      error: true,
    },
  ],
};
